server.port=${PORT:8080}

spring.datasource.url=${db.url}
db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres?user=postgres.prhowplexmxxtprjwhgb&password=postgres%40123