server.port=${PORT:8080}


# C?u hình tr?c ti?p URL và Driver c?a PostgreSQL
spring.datasource.url=jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres?user=postgres.prhowplexmxxtprjwhgb&password=postgres%40123
spring.datasource.driver-class-name=org.postgresql.Driver

# (Tùy ch?n) N?u b?n mu?n b?o m?t m?t kh?u, b?n có th? tách user/password ra nh? sau, nh?ng dùng URL tr?c ti?p nh? trên là nhanh nh?t ?? test:
# spring.datasource.username=postgres.prhowplexmxxtprjwhgb
# spring.datasource.password=postgres@123